2024-10-07 15:50:46,136 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Users\Алексей\PythonProjects\Urban\module 12\HW_12_04\tests_12_4.py", line 23, in test_run
    runner = Runner(2, 5)
             ^^^^^^^^^^^^
  File "D:\Users\Алексей\PythonProjects\Urban\module 12\HW_12_04\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-07 15:50:46,137 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Users\Алексей\PythonProjects\Urban\module 12\HW_12_04\tests_12_4.py", line 13, in test_walk
    runner = Runner('Вася', -5)
             ^^^^^^^^^^^^^^^^^^
  File "D:\Users\Алексей\PythonProjects\Urban\module 12\HW_12_04\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
